In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
from tensorflow.keras.initializers import Zeros
from IPython.display import display

In [24]:
np.random.seed(1992)

N = 11
a = np.zeros((N, N))
w = np.random.normal(0, 1, int(N*(N-1)/2)) # -1 as we remove the diagonal
upper_indices = np.vstack(np.triu_indices(N, k=1))

upper_indices = upper_indices[0, :] * N + upper_indices[1, :]
np.put(a, upper_indices, w)

display(pd.DataFrame(a))

0         1         2         3         4         5         6         7   \
0   0.0 -0.235163  1.078820 -0.426006  0.226979  1.355065  1.091244  0.330408   
1   0.0  0.000000 -0.268059 -1.069692 -1.453324 -0.722493 -1.901867 -0.871000   
2   0.0  0.000000  0.000000 -0.430066 -0.203135 -0.241548  0.228578  0.539409   
3   0.0  0.000000  0.000000  0.000000  0.917942  0.181531 -0.158399 -1.774385   
4   0.0  0.000000  0.000000  0.000000  0.000000 -0.517601 -0.293709 -0.628146   
5   0.0  0.000000  0.000000  0.000000  0.000000  0.000000 -1.241448 -0.131384   
6   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  1.259424   
7   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          8         9         10  
0   2.190902 -0.223310  0.448678  
1  -0.327478  2.880395  0.593235  
2   0.036679  0.530178 -0.262957  
3  -0.945756 -0.559102  0.353913  
4   0.375855  0.239218  0.197808  
5   0.982549 -0.015160 -1.180752  
6  -1.293803 -0.292961 -1.754733  
7   0.764420 -2.295103  2.460652  
8   0.000000  0.009003  0.896342  
9   0.000000  0.000000  1.473940  
10  0.000000  0.000000  0.000000

In [114]:
N = 11

w_init = tf.random_normal_initializer()
zero_init = tf.zeros_initializer()

w = tf.Variable(initial_value = w_init(shape=(int(N*(N-1)/2), ), dtype='float32'), trainable=True)
zero_col_var = tf.Variable(initial_value = zero_init(shape=(N, 1), dtype='float32'), trainable=False) 
zero_row_var = tf.Variable(initial_value = zero_init(shape=(1, N-1), dtype='float32'), trainable=False)

w = tfp.math.fill_triangular(w, upper=True)
w = tf.concat([w, zero_row_var], axis=0)
w = tf.concat([zero_col_var, w], axis=1)

inputs = tf.constant(np.eye(N), dtype='float32')
display(pd.DataFrame(inputs.numpy()))

inputs = tf.tile(inputs, [N, 1])

display(pd.DataFrame(w.numpy()))
display(pd.DataFrame(inputs.numpy()))

# logis = tf.multiply(inputs, w)


# display(pd.DataFrame(np.triu(inputs, k=1)))

# input_mask = tf.linalg.band_part(inputs, )

# res = tf.transpose(tf.transpose(tf.exp(logis))/tf.reduce_sum(tf.exp(logis), axis=1))

# display(pd.DataFrame(res.numpy()))






















0    1    2    3    4    5    6    7    8    9    10
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

0         1         2         3         4         5         6         7   \
0   0.0 -0.052578 -0.050022 -0.027325  0.004602  0.033884 -0.137961  0.017378   
1   0.0  0.000000  0.039399  0.014342  0.028940 -0.020218  0.050483 -0.028118   
2   0.0  0.000000  0.000000  0.072949  0.007610 -0.023103  0.042633  0.018099   
3   0.0  0.000000  0.000000  0.000000 -0.013557 -0.012752 -0.011007 -0.075288   
4   0.0  0.000000  0.000000  0.000000  0.000000 -0.047786  0.004266 -0.008942   
5   0.0  0.000000  0.000000  0.000000  0.000000  0.000000 -0.017437 -0.074588   
6   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000 -0.060544   
7   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          8         9         10  
0   0.107624 -0.109556 -0.051507  
1   0.080778 -0.072664  0.023140  
2  -0.051879  0.049019  0.024557  
3  -0.016242  0.079280 -0.030743  
4   0.054916 -0.011148 -0.053006  
5  -0.064547  0.108113  0.040932  
6   0.036754  0.058711  0.078269  
7  -0.078028 -0.030383  0.054075  
8   0.000000 -0.033696 -0.065491  
9   0.000000  0.000000 -0.038784  
10  0.000000  0.000000  0.000000

0    1    2    3    4    5    6    7    8    9    10
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
116  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
117  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
118  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
119  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
120  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

[121 rows x 11 columns]

In [123]:
t1 = tf.Variable(np.ones((3,3)))
t2 = tf.Variable(1-np.eye(3,3))

t3 = tf.multiply(tf.linalg.band_part(t1, 0, -1), t2)

display(t3)

display(tf.gather(t3, 1, axis=0))

res = tf.gather(t3, 1, axis=0)

display(tf.tile(tf.reshape(res, shape=(1,-1)), [10, 1]))

display(tf.reshape(t3, shape=(1, -1)))


<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])>

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0., 0., 1.])>

<tf.Tensor: shape=(10, 3), dtype=float64, numpy=
array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])>

<tf.Tensor: shape=(1, 9), dtype=float64, numpy=array([[0., 1., 1., 0., 0., 1., 0., 0., 0.]])>